using System.Drawing;
using System.Windows;
using WinForms = System.Windows.Forms;

namespace DotStream.App;

/// <summary>
/// Tray presence.
///
/// Loads the same dotstream.ico the executable and the windows use, so there is one
/// asset and no chance of the tray drifting away from the rest of the app. The file
/// is generated by tools/make-icon.ps1.
/// </summary>
public sealed class TrayIcon : IDisposable
{
    private static readonly Uri IconUri = new("pack://application:,,,/Resources/dotstream.ico");

    private readonly WinForms.NotifyIcon _notifyIcon;
    private readonly Icon _icon;

    public TrayIcon()
    {
        _icon = LoadIcon();

        var menu = new WinForms.ContextMenuStrip();
        menu.Items.Add("Open dotStream", null, (_, _) => OpenRequested?.Invoke(this, EventArgs.Empty));
        menu.Items.Add(new WinForms.ToolStripSeparator());
        menu.Items.Add("Exit", null, (_, _) => ExitRequested?.Invoke(this, EventArgs.Empty));

        _notifyIcon = new WinForms.NotifyIcon
        {
            Icon = _icon,
            Text = "dotStream",
            Visible = true,
            ContextMenuStrip = menu
        };

        _notifyIcon.DoubleClick += (_, _) => OpenRequested?.Invoke(this, EventArgs.Empty);
    }

    public event EventHandler? OpenRequested;

    public event EventHandler? ExitRequested;

    public void ShowBalloon(string title, string message) =>
        _notifyIcon.ShowBalloonTip(4000, title, message, WinForms.ToolTipIcon.Info);

    private static Icon LoadIcon()
    {
        // Ask for the tray size explicitly; the .ico carries 16 through 256, and
        // letting the system pick tends to land on a scaled 32 at high DPI.
        int size = WinForms.SystemInformation.SmallIconSize.Width;

        using System.IO.Stream stream = Application.GetResourceStream(IconUri).Stream;
        return new Icon(stream, new System.Drawing.Size(size, size));
    }

    public void Dispose()
    {
        _notifyIcon.Visible = false;
        _notifyIcon.Dispose();
        _icon.Dispose();
    }
}
