# Generates src/DotStream.Rendering/FluentIcons.g.cs from Fluent UI System Icons.
#
# Only the icons listed below are fetched, so the repository is not vendored - the
# generated file is a few hundred lines of path data and is committed alongside the
# source. Re-run this to add more.
#
# Fluent UI System Icons is MIT licensed (c) Microsoft Corporation, which is why these
# can be shipped at all. The icons in SHELL32.dll cannot: those are read from the
# user's own machine at runtime instead.
#
# Every icon is a single 24x24 path, which is exactly the grid CellRenderer draws on,
# so the path data goes in unchanged.

param(
    [string] $OutputPath = (Join-Path $PSScriptRoot '..\src\DotStream.Rendering\FluentIcons.g.cs')
)

$ErrorActionPreference = 'Stop'

# our name  =  Fluent asset folder
$Icons = [ordered]@{
    'bold'          = 'Text Bold'
    'italic'        = 'Text Italic'
    'underline'     = 'Text Underline'
    'strikethrough' = 'Text Strikethrough'
    'superscript'   = 'Text Superscript'
    'subscript'     = 'Text Subscript'
    'case'          = 'Text Change Case'
    'font'          = 'Text Font'
    'grow'          = 'Font Increase'
    'shrink'        = 'Font Decrease'
    'colour'        = 'Text Color'

    'save'          = 'Save'
    'open'          = 'Folder Open'
    'new'           = 'Document Add'
    'copy'          = 'Copy'
    'cut'           = 'Cut'
    'paste'         = 'Clipboard Paste'
    'undo'          = 'Arrow Undo'
    'redo'          = 'Arrow Redo'
    'find'          = 'Search'
    'replace'       = 'Arrow Swap'
    'delete'        = 'Delete'
    'print'         = 'Print'
    'comment'       = 'Comment'
    'link'          = 'Link'
    'attach'        = 'Attach'
    'image'         = 'Image'
    'chart'         = 'Data Bar Vertical'

    'align-left'    = 'Text Align Left'
    'align-centre'  = 'Text Align Center'
    'align-right'   = 'Text Align Right'
    'list'          = 'Text Bullet List'
    # Note the capitalisation: the repository uses "LTR", not "Ltr".
    'numbered-list' = 'Text Number List LTR'
    'indent'        = 'Text Indent Increase LTR'
    'table'         = 'Table'
    'merge-cells'   = 'Table Cells Merge'
    'text-wrap'     = 'Text Wrap'
    'highlight'     = 'Highlight'
    'paint'         = 'Paint Bucket'
    'sum'           = 'Math Formula'
    'filter'        = 'Filter'
    'sort'          = 'Arrow Sort'
    'zoom'          = 'Zoom In'

    'check'         = 'Checkmark'
    'cross'         = 'Dismiss'
    'star'          = 'Star'
    'lock'          = 'Lock Closed'
    'refresh'       = 'Arrow Sync'
    'settings'      = 'Settings'
    'warning'       = 'Warning'
    'info'          = 'Info'
    'back'          = 'Arrow Left'
    'forward'       = 'Arrow Right'
    'home'          = 'Home'
    'plus'          = 'Add'
    'minus'         = 'Subtract'
    'send'          = 'Send'
    'timer'         = 'Timer'
    'calendar'      = 'Calendar LTR'
    'mail'          = 'Mail'
    'person'        = 'Person'
    'bot'           = 'Bot'

    'play'          = 'Play'
    'pause'         = 'Pause'
    'next'          = 'Next'
    'previous'      = 'Previous'
    'volume-up'     = 'Speaker 2'
    'volume-down'   = 'Speaker 1'
    'mute'          = 'Speaker Off'
    'record'        = 'Record'
    'camera'        = 'Camera'
    'microphone'    = 'Mic'
    'screenshot'    = 'Screenshot'
}

function Get-IconPath([string] $folder) {
    $stem = ($folder.ToLowerInvariant() -replace '[^a-z0-9]+', '_').Trim('_')
    $file = "ic_fluent_${stem}_24_regular.svg"
    $url = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets/" +
           [uri]::EscapeDataString($folder) + "/SVG/" + $file

    $svg = (Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 20).Content

    # An icon may be drawn from more than one subpath; concatenating them is valid
    # because every d string starts with its own move command.
    $matches = [regex]::Matches($svg, '\sd="([^"]+)"')
    if ($matches.Count -eq 0) { throw "no path data" }

    return (($matches | ForEach-Object { $_.Groups[1].Value }) -join ' ')
}

$results = [ordered]@{}
$failed = @()

foreach ($name in $Icons.Keys) {
    try {
        $results[$name] = Get-IconPath $Icons[$name]
        Write-Host ("  {0,-16} {1}" -f $name, $Icons[$name]) -ForegroundColor DarkGray
    } catch {
        $failed += "{0,-16} {1}  ({2})" -f $name, $Icons[$name], $_.Exception.Message.Split([Environment]::NewLine)[0]
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//   Generated by tools/fetch-fluent-icons.ps1 - do not edit by hand.')
[void]$sb.AppendLine('//')
[void]$sb.AppendLine('//   Fluent UI System Icons')
[void]$sb.AppendLine('//   Copyright (c) 2020 Microsoft Corporation')
[void]$sb.AppendLine('//   Licensed under the MIT License. See CREDITS.md.')
[void]$sb.AppendLine('//   https://github.com/microsoft/fluentui-system-icons')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
# Generated files sit outside the project's nullable context unless they say so.
[void]$sb.AppendLine('#nullable enable')
[void]$sb.AppendLine()
[void]$sb.AppendLine('using System.Windows.Media;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace DotStream.Rendering;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// Fluent UI System Icons, as frozen geometry on a 24x24 grid - the same grid')
[void]$sb.AppendLine('/// CellRenderer draws on, so the path data is used unchanged.')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('public static class FluentIcons')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    private static readonly Dictionary<string, Geometry> Cache = [];')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    public static IReadOnlyList<string> Names { get; } =')
[void]$sb.AppendLine('    [')
foreach ($name in $results.Keys) { [void]$sb.AppendLine("        `"$name`",") }
[void]$sb.AppendLine('    ];')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    public static Geometry? Get(string name)')
[void]$sb.AppendLine('    {')
[void]$sb.AppendLine('        if (Cache.TryGetValue(name, out Geometry? cached)) return cached;')
[void]$sb.AppendLine('        if (!Paths.TryGetValue(name, out string? data)) return null;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        // F1 selects the nonzero fill rule. Geometry.Parse defaults to even-odd,')
[void]$sb.AppendLine('        // which turns every counter and hole in these icons inside out.')
[void]$sb.AppendLine('        Geometry geometry = Geometry.Parse("F1 " + data);')
[void]$sb.AppendLine('        geometry.Freeze();')
[void]$sb.AppendLine()
[void]$sb.AppendLine('        Cache[name] = geometry;')
[void]$sb.AppendLine('        return geometry;')
[void]$sb.AppendLine('    }')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    private static readonly Dictionary<string, string> Paths = new()')
[void]$sb.AppendLine('    {')
foreach ($name in $results.Keys) {
    $d = $results[$name] -replace '"', '\"'
    [void]$sb.AppendLine("        [`"$name`"] = `"$d`",")
}
[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')

$dir = Split-Path $OutputPath -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
Set-Content -Path $OutputPath -Value $sb.ToString() -Encoding utf8

""
"fetched $($results.Count) icons -> $((Resolve-Path $OutputPath).Path)"
if ($failed.Count -gt 0) {
    ""
    "FAILED ($($failed.Count)):"
    $failed | ForEach-Object { "  $_" }
}
